<?php

namespace SenseiTarzan\Drawer\Block;

use pocketmine\block\Transparent;
use pocketmine\block\utils\FacesOppositePlacingPlayerTrait;
use pocketmine\block\utils\HorizontalFacingTrait;
use pocketmine\item\Item;
use pocketmine\nbt\tag\CompoundTag;
use SenseiTarzan\Drawer\Tile\DrawerTile;
final class DrawerBlock extends Transparent
{

    use FacesOppositePlacingPlayerTrait;
    use HorizontalFacingTrait;

    public function getSilkTouchDrops(Item $item): array
    {
        return [$this->getPickedItem(true)];
    }

    public function isAffectedBySilkTouch(): bool
    {
        return true;
    }

    public function getDropsForCompatibleTool(Item $item): array
    {
        $items = [$this->asItem()];
        $tile = $this->position->getWorld()->getTile($this->position);
        if ($tile instanceof DrawerTile) {
            if ($tile->hasStock()) {
                $items[] = $tile->getStock();
            }
        }
        return $items; // TODO: Change the autogenerated stub
    }

    public function getDropsForIncompatibleTool(Item $item): array
    {
        $items = [];
        $tile = $this->position->getWorld()->getTile($this->position);
        if ($tile instanceof DrawerTile) {
            if ($tile->hasStock()) {
                $items[] = $tile->getStock();
            }
        }
        return $items; // TODO: Change the autogenerated stub
    }

    /**
     * Returns the item that players will equip when middle-clicking on this block.
     * If addUserData is true, additional data may be added, such as banner patterns, chest contents, etc.
     */
    public function getPickedItem(bool $addUserData = false): Item
    {
        $item = $this->asItem();
        if ($addUserData) {
            $tile = $this->position->getWorld()->getTile($this->position);
            if ($tile instanceof DrawerTile) {
                $nbt = $tile->getCleanedNBT();
                if ($nbt instanceof CompoundTag) {
                    $item->setCustomBlockData($nbt);
                    $item->setLore([$tile->getStock()->getCount() . "x" . $tile->getStock()->getVanillaName()]);
                }
            }
        }
        return $item;
    }
}